import argparse
import os
import struct

# Custom Twelfth Archive (.twa) Binary Format Specification (Obfuscated):
# -------------------------------------------------------------------
# Unobfuscated Header:
#   [12 bytes] Obfuscation Key: Randomly generated bytes
#
# Obfuscated Payload (XORed with the 12-byte key):
#   [4 bytes] Magic Number: "TWA1" (Twelfth Archive v1)
#   [4 bytes] File Count: Unsigned int (little-endian)
#
#   For each file:
#     [2 bytes] Filename Length (N): Unsigned short (little-endian)
#     [N bytes] Filename: UTF-8 Encoded string
#     [4 bytes] Data Length (M): Unsigned int (little-endian)
#     [M bytes] File Data: Raw bytes of the file
# -------------------------------------------------------------------


def xor_obfuscate(data, key):
    """Obfuscates byte data using a rolling XOR with the provided key."""
    key_len = len(key)
    return bytes([b ^ key[i % key_len] for i, b in enumerate(data)])


def pack_archive(input_paths, output_path=None):
    if not input_paths:
        print("Error: No input paths provided.")
        return

    # Determine default output path if none is provided
    if not output_path:
        first_input_name = os.path.basename(os.path.abspath(input_paths[0]))
        if not first_input_name:  # Handle edge cases like root directory '/'
            first_input_name = "archive"

        # Strip existing extension if it's a file
        if os.path.isfile(input_paths[0]):
            first_input_name, _ = os.path.splitext(first_input_name)

        output_path = f"{first_input_name}.twa"

    # Enforce the .twa extension
    if not output_path.lower().endswith(".twa"):
        output_path += ".twa"

    print(f"Creating Twelfth Archive: '{output_path}'...")

    # First pass: Collect all files to pack so we can count them for the header
    files_to_pack = []

    for path in input_paths:
        abs_path = os.path.abspath(path)

        if not os.path.exists(abs_path):
            print(f"  [!] Warning: Path '{path}' does not exist. Skipping.")
            continue

        if os.path.isfile(abs_path):
            # Add single file
            arc_name = os.path.basename(abs_path)
            files_to_pack.append((abs_path, arc_name))

        elif os.path.isdir(abs_path):
            # Add directory contents recursively
            print(f"  Scanning directory: '{path}'...")
            base_dir = os.path.dirname(abs_path)

            for root, dirs, files in os.walk(abs_path):
                for file in files:
                    file_path = os.path.join(root, file)
                    # Create a relative path so the archive maintains internal folder structure
                    arc_name = os.path.relpath(file_path, base_dir)
                    files_to_pack.append((file_path, arc_name))

    if not files_to_pack:
        print("\nError: No valid files were found to pack.")
        return

    try:
        # Build the payload in memory first so we can obfuscate it
        payload = bytearray()

        # Write Magic Number
        payload.extend(b"TWA1")

        # Write File Count (Unsigned Int, Little-Endian)
        payload.extend(struct.pack("<I", len(files_to_pack)))

        for file_path, arc_name in files_to_pack:
            # Standardize path separators to forward slashes for cross-platform compatibility
            arc_name = arc_name.replace("\\", "/")
            encoded_name = arc_name.encode("utf-8")

            with open(file_path, "rb") as f:
                file_data = f.read()

            # Write Filename Length (Unsigned Short, Little-Endian)
            payload.extend(struct.pack("<H", len(encoded_name)))

            # Write Filename
            payload.extend(encoded_name)

            # Write Data Length (Unsigned Int, Little-Endian)
            payload.extend(struct.pack("<I", len(file_data)))

            # Write Data
            payload.extend(file_data)

            print(f"  + Added: {arc_name}")

        # Generate a random 12-byte obfuscation key
        obfuscation_key = os.urandom(12)

        # Obfuscate the payload using the key
        obfuscated_payload = xor_obfuscate(payload, obfuscation_key)

        # Write the final file: 12-byte key + obfuscated payload
        with open(output_path, "wb") as twa_file:
            twa_file.write(obfuscation_key)
            twa_file.write(obfuscated_payload)

        print(
            f"\nSuccess! Packaged {len(files_to_pack)} file(s) into obfuscated binary archive '{output_path}'."
        )
        print(f"Obfuscation Key (Hex): {obfuscation_key.hex()}")

    except Exception as e:
        print(f"Error creating archive: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Twelfth Engine Archive Packer: Packages any files and directories into an obfuscated .twa binary archive."
    )
    parser.add_argument(
        "input_paths",
        nargs="+",
        help="One or more files or directories to pack into the archive.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Optional output path for the archive. Defaults to <first_input_name>.twa",
        default=None,
    )

    args = parser.parse_args()
    pack_archive(args.input_paths, args.output)
