import argparse
import os
import struct

# Custom Twelfth Model (.twm) Binary Format Specification (Obfuscated):
# -------------------------------------------------------------------
# Unobfuscated Header:
#   [12 bytes] Obfuscation Key: Randomly generated bytes
#
# Obfuscated Payload (XORed with the 12-byte key):
#   [4 bytes] Magic Number: "TWM1" (Twelfth Model v1)
#   [4 bytes] File Count: Unsigned int (little-endian)
#
#   For each file:
#     [2 bytes] Filename Length (N): Unsigned short (little-endian)
#     [N bytes] Filename: UTF-8 Encoded string
#     [4 bytes] Data Length (M): Unsigned int (little-endian)
#     [M bytes] File Data: Raw bytes of the file
# -------------------------------------------------------------------


def xor_obfuscate(data, key):
    """Obfuscates byte data using a rolling XOR with the provided key."""
    key_len = len(key)
    return bytes([b ^ key[i % key_len] for i, b in enumerate(data)])


def pack_model(obj_path, output_path=None):
    if not os.path.exists(obj_path):
        print(f"Error: OBJ file '{obj_path}' not found.")
        return

    # Determine base directory to resolve relative paths inside the OBJ and MTL
    base_dir = os.path.dirname(os.path.abspath(obj_path))
    obj_filename = os.path.basename(obj_path)

    # Set default output path to <obj_name>.twm in the same directory
    if not output_path:
        name, _ = os.path.splitext(obj_filename)
        output_path = os.path.join(base_dir, f"{name}.twm")

    # Set of absolute paths to avoid packing duplicates
    files_to_pack = set()
    files_to_pack.add(os.path.abspath(obj_path))

    mtl_files = []

    # Step 1: Parse the OBJ file to find MTL references
    print(f"Scanning '{obj_filename}' for material libraries...")
    try:
        with open(obj_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("mtllib "):
                    # Extract the MTL filename (can contain spaces)
                    mtl_name = line.split(" ", 1)[1].strip()
                    mtl_path = os.path.join(base_dir, mtl_name)

                    if os.path.exists(mtl_path):
                        mtl_files.append(mtl_path)
                        files_to_pack.add(os.path.abspath(mtl_path))
                    else:
                        print(
                            f"  [!] Warning: MTL file '{mtl_name}' referenced but not found."
                        )
    except Exception as e:
        print(f"Error reading OBJ file: {e}")
        return

    # Step 2: Parse all discovered MTL files to find texture references
    texture_keys = [
        "map_Kd",
        "map_Ks",
        "map_Ka",
        "map_Ke",
        "map_Ns",
        "map_d",
        "map_bump",
        "bump",
        "disp",
        "refl",
        "norm",
    ]

    for mtl_path in mtl_files:
        mtl_filename = os.path.basename(mtl_path)
        mtl_dir = os.path.dirname(mtl_path)
        print(f"Scanning '{mtl_filename}' for textures...")

        try:
            with open(mtl_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue

                    parts = line.split()
                    if parts[0] in texture_keys:
                        # The texture file is usually the last argument on the line
                        tex_name = parts[-1]
                        tex_path = os.path.join(mtl_dir, tex_name)

                        if os.path.exists(tex_path):
                            files_to_pack.add(os.path.abspath(tex_path))
                        else:
                            print(
                                f"  [!] Warning: Texture '{tex_name}' referenced in '{mtl_filename}' not found."
                            )
        except Exception as e:
            print(f"Error reading MTL file '{mtl_filename}': {e}")

    # Step 3: Package all discovered files into the custom .twm binary format
    print(
        f"\nPackaging {len(files_to_pack)} files into '{os.path.basename(output_path)}'..."
    )

    try:
        # Build the payload in memory first so we can obfuscate it
        payload = bytearray()

        # Write Magic Number
        payload.extend(b"TWM1")

        # Write File Count (Unsigned Int, Little-Endian)
        payload.extend(struct.pack("<I", len(files_to_pack)))

        for file_path in files_to_pack:
            # Store files relative to the OBJ's directory to preserve folder structures
            arc_name = os.path.relpath(file_path, base_dir)

            # Standardize path separators to forward slashes for cross-platform compatibility
            arc_name = arc_name.replace("\\", "/")
            encoded_name = arc_name.encode("utf-8")

            with open(file_path, "rb") as f:
                file_data = f.read()

            # Write Filename Length (Unsigned Short, Little-Endian)
            payload.extend(struct.pack("<H", len(encoded_name)))

            # Write Filename
            payload.extend(encoded_name)

            # Write Data Length (Unsigned Int, Little-Endian)
            payload.extend(struct.pack("<I", len(file_data)))

            # Write Data
            payload.extend(file_data)

            print(f"  + Added: {arc_name}")

        # Generate a random 12-byte obfuscation key
        obfuscation_key = os.urandom(12)

        # Obfuscate the payload using the key
        obfuscated_payload = xor_obfuscate(payload, obfuscation_key)

        # Write the final file: 12-byte key + obfuscated payload
        with open(output_path, "wb") as twm_file:
            twm_file.write(obfuscation_key)
            twm_file.write(obfuscated_payload)

        print(f"\nSuccess! Created obfuscated model archive: {output_path}")
        print(f"Obfuscation Key (Hex): {obfuscation_key.hex()}")

    except Exception as e:
        print(f"Error creating archive: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Twelfth Engine Model Packer: Packages an OBJ, its MTL, and textures into an obfuscated .twm binary file."
    )
    parser.add_argument("obj_file", help="Path to the input .obj file")
    parser.add_argument(
        "-o", "--output", help="Optional output path for the .twm binary file"
    )

    args = parser.parse_args()
    pack_model(args.obj_file, args.output)
